"""Tests for gate.sh as generated by scripts/install.sh.

styx.pyz is replaced by a fake that records its arguments, so these tests
check gate.sh itself: which commands it allows, and that emergency runs are
detached from the SSH session while other modes stay in the foreground.
"""

import os
import re
import shutil
import subprocess
import tempfile
import textwrap
import time
import unittest

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

# Records its arguments, then sleeps or exits as told by FAKE_SLEEP / FAKE_RC.
_FAKE_PYZ = textwrap.dedent('''\
    import os, sys, time
    with open(os.path.join(os.path.dirname(__file__), 'calls'), 'a') as f:
        f.write(' '.join(sys.argv[1:]) + '\\n')
    print('fake styx running')
    time.sleep(float(os.environ.get('FAKE_SLEEP', '0')))
    sys.exit(int(os.environ.get('FAKE_RC', '0')))
''')


def _gate_script():
    with open(os.path.join(_REPO_ROOT, 'scripts', 'install.sh')) as f:
        m = re.search(r"cat <<'GATE'\n(.*?)\nGATE\n", f.read(), re.S)
    return m.group(1) + '\n'


class TestGate(unittest.TestCase):

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.gate = os.path.join(self.dir, 'gate.sh')
        with open(self.gate, 'w') as f:
            f.write(_gate_script())
        os.chmod(self.gate, 0o755)
        with open(os.path.join(self.dir, 'styx.pyz'), 'w') as f:
            f.write(_FAKE_PYZ)

    def tearDown(self):
        subprocess.run(['pkill', '-f', os.path.join(self.dir, 'styx.pyz')],
                       capture_output=True)
        shutil.rmtree(self.dir, ignore_errors=True)

    def _gate(self, command, **env):
        full_env = dict(os.environ, SSH_ORIGINAL_COMMAND=command, **env)
        return subprocess.run([self.gate], env=full_env, capture_output=True,
                              text=True, timeout=30)

    def _calls(self):
        path = os.path.join(self.dir, 'calls')
        if not os.path.exists(path):
            return []
        with open(path) as f:
            return f.read().splitlines()

    def test_rejects_other_commands(self):
        r = self._gate('vm-shutdown 100')
        self.assertEqual(r.returncode, 1)
        self.assertIn("only 'orchestrate'", r.stderr)
        self.assertEqual(self._calls(), [])

    def test_dry_run_stays_in_foreground(self):
        r = self._gate('orchestrate --mode dry-run', FAKE_RC='3')
        self.assertEqual(r.returncode, 3)
        self.assertIn('fake styx running', r.stdout)
        self.assertEqual(self._calls(), ['orchestrate --mode dry-run'])

    def test_default_mode_stays_in_foreground(self):
        r = self._gate('orchestrate')
        self.assertEqual(r.returncode, 0)
        self.assertIn('fake styx running', r.stdout)

    def test_maintenance_stays_in_foreground(self):
        r = self._gate('orchestrate --mode maintenance')
        self.assertIn('fake styx running', r.stdout)
        self.assertNotIn('detached', r.stdout)

    @unittest.skipUnless(shutil.which('setsid'), 'setsid not available')
    def test_emergency_is_detached(self):
        start = time.monotonic()
        r = self._gate('orchestrate --mode emergency', FAKE_SLEEP='30')
        self.assertLess(time.monotonic() - start, 10)
        self.assertEqual(r.returncode, 0, msg=r.stderr)
        self.assertIn('started detached', r.stdout)
        self.assertNotIn('fake styx running', r.stdout)
        self.assertEqual(self._calls(), ['orchestrate --mode emergency'])
        pid = int(re.search(r'pid (\d+)', r.stdout).group(1))
        os.kill(pid, 0)   # still running after the gate returned

    @unittest.skipUnless(shutil.which('setsid'), 'setsid not available')
    def test_emergency_mode_equals_form_is_detached(self):
        r = self._gate('orchestrate --phase 2 --mode=emergency', FAKE_SLEEP='30')
        self.assertIn('started detached', r.stdout)

    @unittest.skipUnless(shutil.which('setsid'), 'setsid not available')
    def test_emergency_immediate_failure_is_reported(self):
        r = self._gate('orchestrate --mode emergency', FAKE_RC='2')
        self.assertEqual(r.returncode, 2)
        self.assertIn('exited with status 2', r.stderr)

    @unittest.skipUnless(shutil.which('setsid'), 'setsid not available')
    def test_emergency_not_started_twice(self):
        first = self._gate('orchestrate --mode emergency', FAKE_SLEEP='30')
        self.assertIn('started detached', first.stdout)
        second = self._gate('orchestrate --mode emergency', FAKE_SLEEP='30')
        self.assertEqual(second.returncode, 0)
        self.assertIn('already running', second.stdout)
        self.assertEqual(len(self._calls()), 1)


if __name__ == '__main__':
    unittest.main()
